#ifndef __LOGIC_CONFIG_H__
#define __LOGIC_CONFIG_H__

#define MAX_MESSAGE_CACHE 64

#define BULLET_MAX_DISTANCE 500

#define NPC_TRIGGER_DISTANCE 300
#define NPC_REMOVE_COUNTDOWN 3.0f
#endif //__LOGIC_CONFIG_H__